which: no nvcc in (/cvmfs/sft.cern.ch/lcg/releases/cuda/12.4-4899e/x86_64-el9-gcc11-opt/bin:/cvmfs/sft.cern.ch/lcg/releases/LCG_106_cuda/cuda/12.4/x86_64-el9-gcc11-opt/bin:/cvmfs/sft.cern.ch/lcg/releases/gcc/11.3.0-de683/x86_64-el9/bin:/cvmfs/sft.cern.ch/lcg/releases/binutils/2.40-acaab/x86_64-el9/bin:/nfs/dust/cms/user/puschman/rivet/bin:/nfs/dust/cms/user/puschman/rivet/lib64/../bin:/nfs/dust/cms/user/puschman/tf_venv/bin:/cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.32.02/x86_64-almalinux9.4-gcc114-opt/bin:/cvmfs/sft.cern.ch/lcg/releases/LCG_106_cuda/CMake/3.26.2/x86_64-el9-gcc11-opt/bin:/cvmfs/sft.cern.ch/lcg/releases/gcc/11.3.0-de683/x86_64-el9/bin:/cvmfs/sft.cern.ch/lcg/releases/binutils/2.40-acaab/x86_64-el9/bin:/usr/share/Modules/bin:/afs/desy.de/common/passwd:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin)
2024-08-28 13:03:55.092066: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2024-08-28 13:03:55.093093: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: batchg005.desy.de
2024-08-28 13:03:55.093151: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: batchg005.desy.de
2024-08-28 13:03:55.093306: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 560.28.3
2024-08-28 13:03:55.093337: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 560.28.3
2024-08-28 13:03:55.093346: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 560.28.3
usage: submit_DCTR_training_neural_positive_MSE_vs_BCE.py [-h] [--pid PID]
submit_DCTR_training_neural_positive_MSE_vs_BCE.py: error: unrecognized arguments: -p 33
